version: '2'
services:
  eclinic-app:
    image: eclinic
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=https://admin:admin@eclinic-jregistry.herokuapp.com/eureka
      - SPRING_CLOUD_CONFIG_URI=https://admin:admin@eclinic-jregistry.herokuapp.com/config
      - SPRING_DATA_MONGODB_URI=mongodb://eclinic-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=eClinic
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  eclinic-mongodb:
    extends:
      file: mongodb.yml
      service: eclinic-mongodb
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
